CREATE TABLE BUILDING
(
    ID INTEGER PRIMARY KEY NOT NULL IDENTITY,
    NAME VARCHAR(50) NOT NULL
);
CREATE TABLE PERSON
(
    ID INTEGER PRIMARY KEY NOT NULL IDENTITY,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50),
    POSITION_ID INTEGER,
    CONSTRAINT FK4I8OM42NPV2VI0WM6XUT2DJXR FOREIGN KEY (POSITION_ID) REFERENCES POSITION (ID)
);
CREATE TABLE POSITION
(
    ID INTEGER PRIMARY KEY NOT NULL IDENTITY,
    TITLE VARCHAR(50) NOT NULL
);
CREATE TABLE WAGE
(
    ID INTEGER PRIMARY KEY NOT NULL IDENTITY,
    PRICE DOUBLE,
    START_DATE TIMESTAMP NOT NULL,
    POSITION_ID INTEGER,
    CONSTRAINT FK43TV7I7RUDH7ONFP7QJ5X4L0A FOREIGN KEY (POSITION_ID) REFERENCES POSITION (ID)
);
CREATE TABLE WORK
(
    ID BIGINT PRIMARY KEY NOT NULL IDENTITY,
    DATE TIMESTAMP,
    WORK_PER_DAY INTEGER NOT NULL,
    BUILDING_ID INTEGER,
    PERSON_ID INTEGER,
    CONSTRAINT FKFTN0BORXBGJNBD28OHUF9NBED FOREIGN KEY (BUILDING_ID) REFERENCES BUILDING (ID),
    CONSTRAINT FKMWNXLPLHSQ3J4KYIPVBKU7MWI FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID)
);