-- For Not Null or Null We Use Set -- USE HSQLDB Editor To See The Generated Query
ALTER TABLE PUBLIC.WORK ALTER COLUMN WORK_PER_DAY FLOAT;

ALTER TABLE "PUBLIC"."WORK" DROP CONSTRAINT FKFTN0BORXBGJNBD28OHUF9NBED;
ALTER TABLE "PUBLIC"."WORK" DROP CONSTRAINT FKMWNXLPLHSQ3J4KYIPVBKU7MWI;
ALTER TABLE "PUBLIC"."WORK" ADD CONSTRAINT FK_WORK_BUILDING FOREIGN KEY (BUILDING_ID) REFERENCES "PUBLIC"."BUILDING" (ID);
ALTER TABLE "PUBLIC"."WORK" ADD CONSTRAINT FK_WORK_PERSON FOREIGN KEY (PERSON_ID) REFERENCES "PUBLIC"."PERSON" (ID);

ALTER TABLE "PUBLIC"."WAGE" DROP CONSTRAINT FK43TV7I7RUDH7ONFP7QJ5X4L0A;
ALTER TABLE "PUBLIC"."WAGE" ADD CONSTRAINT FK_WAGE_POSITION FOREIGN KEY (POSITION_ID) REFERENCES "PUBLIC"."POSITION" (ID);

ALTER TABLE "PUBLIC"."PERSON" DROP CONSTRAINT FK4I8OM42NPV2VI0WM6XUT2DJXR;
ALTER TABLE "PUBLIC"."PERSON" ADD CONSTRAINT FK_PERSON_POSITION FOREIGN KEY (POSITION_ID) REFERENCES "PUBLIC"."POSITION" (ID);