CREATE TABLE BUILDING
(
    ID INTEGER PRIMARY KEY NOT NULL IDENTITY,
    NAME VARCHAR(50) NOT NULL
);
CREATE TABLE PERSON
(
    ID INTEGER PRIMARY KEY NOT NULL IDENTITY,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50),
    POSITION_ID INTEGER,
    CONSTRAINT FK_PERSON_POSITION FOREIGN KEY (POSITION_ID) REFERENCES POSITION (ID)
);
CREATE TABLE POSITION
(
    ID INTEGER PRIMARY KEY NOT NULL IDENTITY,
    TITLE VARCHAR(50) NOT NULL
);
CREATE TABLE "schema_version"
(
    "installed_rank" INTEGER PRIMARY KEY NOT NULL,
    "version" VARCHAR(50),
    "description" VARCHAR(200) NOT NULL,
    "type" VARCHAR(20) NOT NULL,
    "script" VARCHAR(1000) NOT NULL,
    "checksum" INTEGER,
    "installed_by" VARCHAR(100) NOT NULL,
    "installed_on" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "execution_time" INTEGER NOT NULL,
    "success" BIT NOT NULL
);
CREATE INDEX "schema_version_s_idx" ON "schema_version" ("success");
CREATE TABLE WAGE
(
    ID INTEGER PRIMARY KEY NOT NULL IDENTITY,
    PRICE DOUBLE,
    START_DATE TIMESTAMP NOT NULL,
    POSITION_ID INTEGER,
    CONSTRAINT FK_WAGE_POSITION FOREIGN KEY (POSITION_ID) REFERENCES POSITION (ID)
);
CREATE TABLE WORK
(
    ID BIGINT PRIMARY KEY NOT NULL IDENTITY,
    DATE TIMESTAMP,
    WORK_PER_DAY DOUBLE NOT NULL,
    BUILDING_ID INTEGER,
    PERSON_ID INTEGER,
    CONSTRAINT FK_WORK_BUILDING FOREIGN KEY (BUILDING_ID) REFERENCES BUILDING (ID),
    CONSTRAINT FK_WORK_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID)
);